publishing {
    publications {
        mavenJava(MavenPublication) {
            if (project.hasProperty("releaseJarFile")) {
                artifact file(project.property("releaseJarFile"))
            } else {
                artifact tasks.named("releaseJar")
            }
            pom {
                name = mod_name
                description = mod_description
                url = mod_url
                licenses {
                    license {
                        name = mod_license
                        url = 'https://www.gnu.org/licenses/lgpl-3.0.txt'
                    }
                }
                issueManagement {
                    system = 'GitHub'
                    url = mod_issue_tracker
                }
            }
        }
    }

	if (System.getenv("MAVEN_URL")) {
		repositories {
			maven {
				name = "release"
				url = uri(System.getenv("MAVEN_URL"))
				credentials {
					username = System.getenv("MAVEN_USER")
					password = System.getenv("MAVEN_PASSWORD")
				}
			}
		}
	}
}
