name: Build and Test PR

on:
  pull_request:
    paths: ['**']

concurrency:
  group: PR-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_SUFFIX: PR-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - '*.gradle'
              - 'gradle.properties'
              - 'gradlew*'
              - 'gradle/**'
      - name: Install native dependencies
        if: steps.filter.outputs.code == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev cmake
      - name: Setup Build
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/build_setup
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build native + JAR
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew assemble -x test
      - name: Upload native libs
        if: steps.filter.outputs.code == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: native-libs
          path: native/
          retention-days: 1
      - name: Rename Jars
        if: steps.filter.outputs.code == 'true'
        run: for file in build/libs/*; do mv "$file" "${file/.jar/-${{ env.VERSION_SUFFIX }}.jar}"; done;
      - name: Upload JAR
        if: steps.filter.outputs.code == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Bigmath-FFM-PR-${{ github.event.number }}
          path: build/libs/*
          retention-days: 15

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download native libs
        uses: actions/download-artifact@v4
        with:
          name: native-libs
          path: ./
      - name: Setup Build
        uses: ./.github/actions/build_setup
      - run: chmod +x gradlew
      - name: Run Tests
        id: test
        continue-on-error: true
        run: ./gradlew test -PrunTests -x buildNative -x cmakeConfigure -x copyNativeLib
      - name: Update "Tests Passed" / "Tests Failed" labels
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v7
        with:
          script: |
            const [add, remove] = {
              success: ['Tests: Passed','Tests: Failed'],
              failure: ['Tests: Failed','Tests: Passed']
            }['${{ steps.test.outcome }}'];

            const { owner, repo }    = context.repo;
            const issue_number       = context.payload.pull_request.number;

            await github.rest.issues
              .addLabels({ owner, repo, issue_number, labels: [add] })
              .catch(() => {});

            await github.rest.issues
              .removeLabel({ owner, repo, issue_number, name: remove })
              .catch(() => {});
      - name: Fail on test failures
        if: steps.test.outcome == 'failure'
        run: exit 1
