name: Build pull request on push

on:
  pull_request:
    paths: ['**']

concurrency:
  group: PR-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_SUFFIX: PR-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - '*.gradle'
              - 'gradle.properties'
              - 'gradlew*'
              - 'gradle/**'
      - name: Install native dependencies
        if: steps.filter.outputs.code == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev cmake
      - name: Setup Build
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/build_setup
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Test
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew build -PrunTests
      - name: Rename Jars
        if: steps.filter.outputs.code == 'true'
        run: for file in build/libs/*; do mv "$file" "${file/.jar/-${{ env.VERSION_SUFFIX }}.jar}"; done;
      - name: Upload Artifacts
        if: steps.filter.outputs.code == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Bigmath-FFM-PR-${{ github.event.number }}
          path: build/libs/*
          retention-days: 15
