name: Publish on Release

on:
  release:
    types: [released]

jobs:
  meta:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      CHANGELOG: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Get Config
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          sparse-checkout: '.github/json'
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: './.github/json/config.json'
          ignorePreReleases: true
          fetchViaCommits: true
          failOnError: false

  publish:
    name: Publish to Maven
    needs: [meta]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Build
        uses: ./.github/actions/build_setup
        with:
          update-cache: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish -x buildNative -x test
        shell: bash
        env:
          ORG_GRADLE_PROJECT_bigmath_skipNative: true
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Update release body
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release edit ${{ github.ref_name }} \
            --notes-file <(echo "${{ needs.meta.outputs.CHANGELOG }}")
