name: Publish on Release

on:
  release:
    types: [prereleased, released]

jobs:
  meta:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      CHANGELOG: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Get Config
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          sparse-checkout: '.github/json'
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: './.github/json/config.json'
          ignorePreReleases: true
          fetchViaCommits: true
          failOnError: false

  publish-26:
    name: Publish 26.1
    needs: [meta]
    if: ${{ contains(github.ref_name, '26.1') && github.event.release.prerelease == false }}
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      simulate: ${{ startsWith(github.event.release.name, 'simulate') || github.repository_owner != 'ModularMCLib' }}
      tag-name: ${{ github.ref_name }}
      version: '26.1'
      release-body: ${{ github.event.release.body }}
      changelog-body: ${{ needs.meta.outputs.CHANGELOG }}

  publish-prerelease-26:
    name: Publish 26.1 Pre-release
    needs: [meta]
    if: ${{ contains(github.ref_name, '26.1') && github.event.release.prerelease == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '26.1'
      - name: Setup Build
        uses: ./.github/actions/build_setup
        with:
          ref: '26.1'
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew assemble -x test
      - name: Upload JARs to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/libs/*.jar
          fail_on_unmatched_files: true
